dbt_on_snow:
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SF_ACCOUNT') }}"
      user: "{{ env_var('SF_USER') }}"
      private_key_path: "{{ env_var('SF_PRIVATE_KEY_PATH') }}"
      role: sysadmin
      database: d_harato_db
      warehouse: d_harato_wh
      schema: public
      threads: 10
    prd:
      type: snowflake
      account: "{{ env_var('SF_ACCOUNT') }}"
      user: "{{ env_var('SF_USER') }}"
      private_key_path: "{{ env_var('SF_PRIVATE_KEY_PATH') }}"
      role: sysadmin
      database: d_harato_db
      warehouse: d_harato_wh
      schema: public
      threads: 10
  target: dev